package com.mouchina.moumou_server.entity.advert;

import java.io.Serializable;

public class AdvertType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_type.id
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_type.name
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert_type.state
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advert_type
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_type.id
     *
     * @return the value of advert_type.id
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_type.id
     *
     * @param id the value for advert_type.id
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_type.name
     *
     * @return the value of advert_type.name
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_type.name
     *
     * @param name the value for advert_type.name
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert_type.state
     *
     * @return the value of advert_type.state
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert_type.state
     *
     * @param state the value for advert_type.state
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setState(Byte state) {
        this.state = state;
    }
}