package com.mouchina.moumou_server.entity.system;

import java.io.Serializable;

public class SystemData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_data.id
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_data.key
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    private String keyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_data.value
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    private Integer sysValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_data.type
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_data
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_data.id
     *
     * @return the value of system_data.id
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_data.id
     *
     * @param id the value for system_data.id
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_data.key
     *
     * @return the value of system_data.key
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_data.key
     *
     * @param keyName the value for system_data.key
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName == null ? null : keyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_data.value
     *
     * @return the value of system_data.value
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    public Integer getSysValue() {
        return sysValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_data.value
     *
     * @param value the value for system_data.value
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    public void setSysValue(Integer value) {
        this.sysValue = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_data.type
     *
     * @return the value of system_data.type
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_data.type
     *
     * @param type the value for system_data.type
     *
     * @mbggenerated Mon Feb 22 18:03:08 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }
}