package com.mouchina.moumou_server.entity.system;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class SystemGlobalConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.id
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.config_key
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    private String configKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.config_name
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.config_content
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    private String configContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.config_max
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    private Integer configMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.config_min
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    private Integer configMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.config_normal
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    private Integer configNormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.config_desc
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    private String configDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.create_time
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_global_config.modify_time
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date modifyTime;
    
    
    private Byte state;

    private String configGroup;

    public String getConfigGroup() {
        return configGroup;
    }

    public void setConfigGroup(String configGroup) {
        this.configGroup = configGroup;
    }

    public Byte getState() {
		return state;
	}

	public void setState(Byte state) {
		this.state = state;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_global_config
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.id
     *
     * @return the value of system_global_config.id
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.id
     *
     * @param id the value for system_global_config.id
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.config_key
     *
     * @return the value of system_global_config.config_key
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.config_key
     *
     * @param configKey the value for system_global_config.config_key
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.config_name
     *
     * @return the value of system_global_config.config_name
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.config_name
     *
     * @param configName the value for system_global_config.config_name
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.config_content
     *
     * @return the value of system_global_config.config_content
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public String getConfigContent() {
        return configContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.config_content
     *
     * @param configContent the value for system_global_config.config_content
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setConfigContent(String configContent) {
        this.configContent = configContent == null ? null : configContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.config_max
     *
     * @return the value of system_global_config.config_max
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public Integer getConfigMax() {
        return configMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.config_max
     *
     * @param configMax the value for system_global_config.config_max
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setConfigMax(Integer configMax) {
        this.configMax = configMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.config_min
     *
     * @return the value of system_global_config.config_min
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public Integer getConfigMin() {
        return configMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.config_min
     *
     * @param configMin the value for system_global_config.config_min
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setConfigMin(Integer configMin) {
        this.configMin = configMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.config_normal
     *
     * @return the value of system_global_config.config_normal
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public Integer getConfigNormal() {
        return configNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.config_normal
     *
     * @param configNormal the value for system_global_config.config_normal
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setConfigNormal(Integer configNormal) {
        this.configNormal = configNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.config_desc
     *
     * @return the value of system_global_config.config_desc
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public String getConfigDesc() {
        return configDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.config_desc
     *
     * @param configDesc the value for system_global_config.config_desc
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setConfigDesc(String configDesc) {
        this.configDesc = configDesc == null ? null : configDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.create_time
     *
     * @return the value of system_global_config.create_time
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.create_time
     *
     * @param createTime the value for system_global_config.create_time
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_global_config.modify_time
     *
     * @return the value of system_global_config.modify_time
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_global_config.modify_time
     *
     * @param modifyTime the value for system_global_config.modify_time
     *
     * @mbggenerated Sun Jul 12 17:46:35 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}