package com.mouchina.web.service.api.vo;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

public class BusinessAdvertVo  implements  Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -856290775777340518L;

	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.id
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
	@JsonProperty("businessId")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.user_id
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
	
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_name
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_address
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String businessAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_tel
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String businessTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_site
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String businessSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_qq
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String businessQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_weixin
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String businessWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_weibo
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String businessWeibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.businss_credentials_up
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
	@JsonIgnore
    private String businssCredentialsUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_credentials_down
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
	@JsonIgnore
    private String businessCredentialsDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.business_credentials_face
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
	@JsonIgnore
    private String businessCredentialsFace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.create_time
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
	@JsonIgnore
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.modfiy_time
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
	@JsonIgnore
    private Date modfiyTime;

	private String descb;
	
    public String getDescb() {
		return descb;
	}

	public void setDescb(String descb) {
		this.descb = descb;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.state
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private Byte state;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getBusinessAddress() {
		return businessAddress;
	}

	public void setBusinessAddress(String businessAddress) {
		this.businessAddress = businessAddress;
	}

	public String getBusinessTel() {
		return businessTel;
	}

	public void setBusinessTel(String businessTel) {
		this.businessTel = businessTel;
	}

	public String getBusinessSite() {
		return businessSite;
	}

	public void setBusinessSite(String businessSite) {
		this.businessSite = businessSite;
	}

	public String getBusinessQq() {
		return businessQq;
	}

	public void setBusinessQq(String businessQq) {
		this.businessQq = businessQq;
	}

	public String getBusinessWeixin() {
		return businessWeixin;
	}

	public void setBusinessWeixin(String businessWeixin) {
		this.businessWeixin = businessWeixin;
	}

	public String getBusinessWeibo() {
		return businessWeibo;
	}

	public void setBusinessWeibo(String businessWeibo) {
		this.businessWeibo = businessWeibo;
	}

	public String getBusinssCredentialsUp() {
		return businssCredentialsUp;
	}

	public void setBusinssCredentialsUp(String businssCredentialsUp) {
		this.businssCredentialsUp = businssCredentialsUp;
	}

	public String getBusinessCredentialsDown() {
		return businessCredentialsDown;
	}

	public void setBusinessCredentialsDown(String businessCredentialsDown) {
		this.businessCredentialsDown = businessCredentialsDown;
	}

	public String getBusinessCredentialsFace() {
		return businessCredentialsFace;
	}

	public void setBusinessCredentialsFace(String businessCredentialsFace) {
		this.businessCredentialsFace = businessCredentialsFace;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModfiyTime() {
		return modfiyTime;
	}

	public void setModfiyTime(Date modfiyTime) {
		this.modfiyTime = modfiyTime;
	}

	public Byte getState() {
		return state;
	}

	public void setState(Byte state) {
		this.state = state;
	}
    
    
}
