package com.mouchina.web.service.api.vo;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UserVo implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2832758239732072364L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.id
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonProperty("userId")
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.table_num
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private Integer tableNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.phone
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */

	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.pass_wrod
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private String passWord;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.create_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.modify_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private Date modifyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.private_key
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private String privateKey;
	private Integer sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.public_key
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private String publicKey;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.token
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private String token;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.name
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.type
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private Byte type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.state
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private Byte state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.role
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private String role;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.identity_card
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private String identityCard;

	/**
	 * This field was generated by MyBatis Generator.
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	private Date birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.avatar
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String avatar;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.mid
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private String mid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.nick_name
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String nickName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.login_expire_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date loginExpireTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.last_login_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private Date lastLoginTime;
	@JsonIgnore
	private String bindingMobile;
	@JsonIgnore
	private String channel;
	@JsonIgnore
	private String platform;

	private String shortDesc;

	private Integer work;

	private String hobby;
	private Byte married;
	private String inventNo;

	private Byte ageGroup;

	private Byte salary;

	private String province; // 省份

	private String city; // 市

	private String area; // 区县

	private String thirdUid;// 第三方标识

	private long mapprervalue;

	private int num;

	private String address;// 详细地址
	
	private int level;//用户等级
	
	private int markType;//用户身份信息 0、未认证  1、个人认证  2、 商户认证 3、区县代理 4、中心代理 5、星级代理
	
	private Integer cashBalance; //剩余广告币
	
	private int growthPoint;//升级所需成长值
	
	private int levelRatio;//福袋金额加成
	
	private int homePageRedEnvelope;//可领取首页福袋个数
	

	private int approveType; //用户认证身份     0 未认证    1个人认证    2商户认证

	private int userIdentity; //用户类型 1个人用户   2商户用户    3商户店铺用户
	
	private int redEnvelopeBalance; //剩余零钱
	
	private String businessName; //商户简称
	
	private Integer receiveState; //首页福袋领取状态(0未领取 1已领取)
	
	private Long advertId; //广告福袋ID
	
	public int getMarkType() {
		return markType;
	}

	public void setMarkType(int markType) {
		this.markType = markType;
	}

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getThirdUid() {
		return thirdUid;
	}

	public void setThirdUid(String thirdUid) {
		this.thirdUid = thirdUid;
	}

	public long getMapprervalue() {
		return mapprervalue;
	}

	public void setMapprervalue(long mapprervalue) {
		this.mapprervalue = mapprervalue;
	}

	public int getNum() {
		return num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Byte getSalary() {
		return salary;
	}

	public void setSalary(Byte salary) {
		this.salary = salary;
	}

	@JsonIgnore
	private Byte incomeLevel;

	public Byte getIncomeLevel() {
		return incomeLevel;
	}

	public void setIncomeLevel(Byte incomeLevel) {
		this.incomeLevel = incomeLevel;
	}

	public Byte getAgeGroup() {
		return ageGroup;
	}

	public void setAgeGroup(Byte ageGroup) {
		this.ageGroup = ageGroup;
	}

	public String getInventNo() {
		return inventNo;
	}

	public void setInventNo(String inventNo) {
		this.inventNo = inventNo;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getTableNum() {
		return tableNum;
	}

	public void setTableNum(Integer tableNum) {
		this.tableNum = tableNum;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPassWord() {
		return passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getPrivateKey() {
		return privateKey;
	}

	public void setPrivateKey(String privateKey) {
		this.privateKey = privateKey;
	}

	public String getPublicKey() {
		return publicKey;
	}

	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Byte getType() {
		return type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	public Byte getState() {
		return state;
	}

	public void setState(Byte state) {
		this.state = state;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getIdentityCard() {
		return identityCard;
	}

	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getMid() {
		return mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public Date getLoginExpireTime() {
		return loginExpireTime;
	}

	public void setLoginExpireTime(Date loginExpireTime) {
		this.loginExpireTime = loginExpireTime;
	}

	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public String getBindingMobile() {
		return bindingMobile;
	}

	public void setBindingMobile(String bindingMobile) {
		this.bindingMobile = bindingMobile;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getPlatform() {
		return platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getShortDesc() {
		return shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public Integer getWork() {
		return work;
	}

	public void setWork(Integer work) {
		this.work = work;
	}

	public String getHobby() {
		return hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public Byte getMarried() {
		return married;
	}

	public void setMarried(Byte married) {
		this.married = married;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Integer getCashBalance() {
		return cashBalance;
	}

	public void setCashBalance(Integer cashBalance) {
		this.cashBalance = cashBalance;
	}

	public int getGrowthPoint() {
		return growthPoint;
	}

	public void setGrowthPoint(int growthPoint) {
		this.growthPoint = growthPoint;
	}

	public int getLevelRatio() {
		return levelRatio;
	}

	public void setLevelRatio(int levelRatio) {
		this.levelRatio = levelRatio;
	}

	public int getHomePageRedEnvelope() {
		return homePageRedEnvelope;
	}

	public void setHomePageRedEnvelope(int homePageRedEnvelope) {
		this.homePageRedEnvelope = homePageRedEnvelope;
	}


	public int getApproveType() {
		return approveType;
	}

	public void setApproveType(int approveType) {
		this.approveType = approveType;
	}

	public int getUserIdentity() {
		return userIdentity;
	}

	public void setUserIdentity(int userIdentity) {
		this.userIdentity = userIdentity;
	}

	public int getRedEnvelopeBalance() {
		return redEnvelopeBalance;
	}

	public void setRedEnvelopeBalance(int redEnvelopeBalance) {
		this.redEnvelopeBalance = redEnvelopeBalance;
	}

	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public Integer getReceiveState() {
		return receiveState;
	}

	public void setReceiveState(Integer receiveState) {
		this.receiveState = receiveState;
	}

	public Long getAdvertId() {
		return advertId;
	}

	public void setAdvertId(Long advertId) {
		this.advertId = advertId;
	}

}
