package com.mouchina.web.service.api.vo;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UsersRelationVo implements Serializable{
	  /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Long relationUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_type
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Byte relationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_user_avatar
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private String relationUserAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_user_sex
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Byte relationUserSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_user_nick_name
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private String relationUserNickName;

    
    private String advertContent;
    
    private String advertName;
    
    
 
   	private String businessName;

   	/**
   	 * This field was generated by MyBatis Generator. This field corresponds to
   	 * the database column business.business_address
   	 * 
   	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
   	 */
   	private String businessAddress;

   	/**
   	 * This field was generated by MyBatis Generator. This field corresponds to
   	 * the database column business.business_tel
   	 * 
   	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
   	 */
   	private String businessTel;

   	/**
   	 * This field was generated by MyBatis Generator. This field corresponds to
   	 * the database column business.business_site
   	 * 
   	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
   	 */
   	private String businessSite;
   	
   	
	private String webSite;
	
	
	

	@JsonProperty("advertId")
	private Long eventId;
	private String businessLogo;
	
	
	
   	public String getBusinessLogo() {
		return businessLogo;
	}

	public void setBusinessLogo(String businessLogo) {
		this.businessLogo = businessLogo;
	}

	public Long getEventId() {
		return eventId;
	}

	public void setEventId(Long eventId) {
		this.eventId = eventId;
	}

	public String getWebSite() {
		return webSite;
	}

	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}

	/**
   	 * This field was generated by MyBatis Generator. This field corresponds to
   	 * the database column business.business_qq
   	 * 
   	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
   	 */
   	private String businessQq;

   	/**
   	 * This field was generated by MyBatis Generator. This field corresponds to
   	 * the database column business.business_weixin
   	 * 
   	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
   	 */
   	private String businessWeixin;

   	/**
   	 * This field was generated by MyBatis Generator. This field corresponds to
   	 * the database column business.business_weibo
   	 * 
   	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
   	 */
   	private String businessWeibo;
   	
   	private String businessDescb;
   	
   	private Integer  isFans;
   	
   	private Long businessId;
   	
   	
    public Long getBusinessId() {
		return businessId;
	}

	public void setBusinessId(Long businessId) {
		this.businessId = businessId;
	}

	public Integer getIsFans() {
		return isFans;
	}

	public void setIsFans(Integer isFans) {
		this.isFans = isFans;
	}

	public String getBusinessDescb() {
		return businessDescb;
	}

	public void setBusinessDescb(String businessDescb) {
		this.businessDescb = businessDescb;
	}

	public String getAdvertName() {
		return advertName;
	}

	public void setAdvertName(String advertName) {
		this.advertName = advertName;
	}

	public String getAdvertContent() {
		return advertContent;
	}

	public void setAdvertContent(String advertContent) {
		this.advertContent = advertContent;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.create_time
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_relation
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.id
     *
     * @return the value of users_relation.id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.id
     *
     * @param id the value for users_relation.id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.user_id
     *
     * @return the value of users_relation.user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.user_id
     *
     * @param userId the value for users_relation.user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_user_id
     *
     * @return the value of users_relation.relation_user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Long getRelationUserId() {
        return relationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_user_id
     *
     * @param relationUserId the value for users_relation.relation_user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationUserId(Long relationUserId) {
        this.relationUserId = relationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_type
     *
     * @return the value of users_relation.relation_type
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Byte getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_type
     *
     * @param relationType the value for users_relation.relation_type
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationType(Byte relationType) {
        this.relationType = relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_user_avatar
     *
     * @return the value of users_relation.relation_user_avatar
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public String getRelationUserAvatar() {
        return relationUserAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_user_avatar
     *
     * @param relationUserAvatar the value for users_relation.relation_user_avatar
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationUserAvatar(String relationUserAvatar) {
        this.relationUserAvatar = relationUserAvatar == null ? null : relationUserAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_user_sex
     *
     * @return the value of users_relation.relation_user_sex
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Byte getRelationUserSex() {
        return relationUserSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_user_sex
     *
     * @param relationUserSex the value for users_relation.relation_user_sex
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationUserSex(Byte relationUserSex) {
        this.relationUserSex = relationUserSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_user_nick_name
     *
     * @return the value of users_relation.relation_user_nick_name
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public String getRelationUserNickName() {
        return relationUserNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_user_nick_name
     *
     * @param relationUserNickName the value for users_relation.relation_user_nick_name
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationUserNickName(String relationUserNickName) {
        this.relationUserNickName = relationUserNickName == null ? null : relationUserNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.create_time
     *
     * @return the value of users_relation.create_time
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.create_time
     *
     * @param createTime the value for users_relation.create_time
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getBusinessAddress() {
		return businessAddress;
	}

	public void setBusinessAddress(String businessAddress) {
		this.businessAddress = businessAddress;
	}

	public String getBusinessTel() {
		return businessTel;
	}

	public void setBusinessTel(String businessTel) {
		this.businessTel = businessTel;
	}

	public String getBusinessSite() {
		return businessSite;
	}

	public void setBusinessSite(String businessSite) {
		this.businessSite = businessSite;
	}

	public String getBusinessQq() {
		return businessQq;
	}

	public void setBusinessQq(String businessQq) {
		this.businessQq = businessQq;
	}

	public String getBusinessWeixin() {
		return businessWeixin;
	}

	public void setBusinessWeixin(String businessWeixin) {
		this.businessWeixin = businessWeixin;
	}

	public String getBusinessWeibo() {
		return businessWeibo;
	}

	public void setBusinessWeibo(String businessWeibo) {
		this.businessWeibo = businessWeibo;
	}

}
