package com.mouchina.web.service.api.vo;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class UserAssetsVo implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7078169422618150800L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_assets_1.id
	 * 
	 * @mbggenerated Mon Jun 15 11:51:20 CST 2015
	 */
	@JsonIgnore
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_assets_1.user_id
	 * 
	 * @mbggenerated Mon Jun 15 11:51:20 CST 2015
	 */
	@JsonIgnore
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_assets_1.cash_coupon_count
	 * 
	 * @mbggenerated Mon Jun 15 11:51:20 CST 2015
	 */
	@JsonIgnore
	private Integer cashCouponCount;
	@JsonIgnore
	private Integer tableNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_assets_1.integral
	 * 
	 * @mbggenerated Mon Jun 15 11:51:20 CST 2015
	 */
	@JsonIgnore
	private Integer integral;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_assets_1.balance
	 * 
	 * @mbggenerated Mon Jun 15 11:51:20 CST 2015
	 */

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_assets_1.price_count
	 * 
	 * @mbggenerated Mon Jun 15 11:51:20 CST 2015
	 */
	@JsonIgnore
	private Integer priceCount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_assets_1.order_count
	 * 
	 * @mbggenerated Mon Jun 15 11:51:20 CST 2015
	 */
	@JsonIgnore
	private Integer orderCount;

	private Integer cashBalance;
	private Integer redEnvelopeBalance;
	
    private double redPackCount;//抢到的红包总数
    
    private int growthValue;//用户成长值
    
    
	public double getRedPackCount() {
		return redPackCount;
	}

	public void setRedPackCount(double redPackCount) {
		this.redPackCount = redPackCount;
	}

	public Long getId() {
		return id;
	}

	public Integer getCashBalance() {
		return cashBalance;
	}

	public void setCashBalance(Integer cashBalance) {
		this.cashBalance = cashBalance;
	}

	public Integer getRedEnvelopeBalance() {
		return redEnvelopeBalance;
	}

	public void setRedEnvelopeBalance(Integer redEnvelopeBalance) {
		this.redEnvelopeBalance = redEnvelopeBalance;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Integer getCashCouponCount() {
		return cashCouponCount;
	}

	public void setCashCouponCount(Integer cashCouponCount) {
		this.cashCouponCount = cashCouponCount;
	}

	public Integer getTableNum() {
		return tableNum;
	}

	public void setTableNum(Integer tableNum) {
		this.tableNum = tableNum;
	}

	public Integer getIntegral() {
		return integral;
	}

	public void setIntegral(Integer integral) {
		this.integral = integral;
	}

	public Integer getPriceCount() {
		return priceCount;
	}

	public void setPriceCount(Integer priceCount) {
		this.priceCount = priceCount;
	}

	public Integer getOrderCount() {
		return orderCount;
	}

	public void setOrderCount(Integer orderCount) {
		this.orderCount = orderCount;
	}

	public int getGrowthValue() {
		return growthValue;
	}

	public void setGrowthValue(int growthValue) {
		this.growthValue = growthValue;
	}

}
