package com.mouchina.moumou_server.entity.member;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class OrderBill implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.id
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.title
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.bill_type
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private Byte billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.company_name
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.state
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.address
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.mail
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.tel
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.create_time
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.amount
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_bill.bak
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private String bak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_bill
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.id
     *
     * @return the value of order_bill.id
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.id
     *
     * @param id the value for order_bill.id
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.title
     *
     * @return the value of order_bill.title
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.title
     *
     * @param title the value for order_bill.title
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.bill_type
     *
     * @return the value of order_bill.bill_type
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public Byte getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.bill_type
     *
     * @param billType the value for order_bill.bill_type
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setBillType(Byte billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.company_name
     *
     * @return the value of order_bill.company_name
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.company_name
     *
     * @param companyName the value for order_bill.company_name
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.state
     *
     * @return the value of order_bill.state
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.state
     *
     * @param state the value for order_bill.state
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.address
     *
     * @return the value of order_bill.address
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.address
     *
     * @param address the value for order_bill.address
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.mail
     *
     * @return the value of order_bill.mail
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.mail
     *
     * @param mail the value for order_bill.mail
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.tel
     *
     * @return the value of order_bill.tel
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.tel
     *
     * @param tel the value for order_bill.tel
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.create_time
     *
     * @return the value of order_bill.create_time
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.create_time
     *
     * @param createTime the value for order_bill.create_time
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.amount
     *
     * @return the value of order_bill.amount
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.amount
     *
     * @param amount the value for order_bill.amount
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_bill.bak
     *
     * @return the value of order_bill.bak
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public String getBak() {
        return bak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_bill.bak
     *
     * @param bak the value for order_bill.bak
     *
     * @mbggenerated Mon Feb 01 16:24:57 CST 2016
     */
    public void setBak(String bak) {
        this.bak = bak == null ? null : bak.trim();
    }
}