package com.mouchina.moumou_server.entity.member;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
	
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.table_num
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private Integer tableNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.phone
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.pass_wrod
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	private String passWord;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.create_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.modify_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private Date modifyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.private_key
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String privateKey;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.public_key
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String publicKey;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.token
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String token;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.name
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.type
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private Byte type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.state
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private Byte state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.role
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String role;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.identity_card
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String identityCard;

	/**
	 * This field was generated by MyBatis Generator.
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	private Date birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.avatar
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String avatar;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.mid
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String mid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.nick_name
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private String nickName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.login_expire_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private Date loginExpireTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.last_login_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private Date lastLoginTime;
	/**
	 * 首次登录时间
	 */
	private Date fristLoginTime;
	/**
	 * 登录手机规格
	 */
	private String phoneSpecification;
	/**
	 * 红包金额
	 */
	private int redpackMoney;
	private String bindingMobile;

	private String channel;
	private String platform;

	
	
	private String shortDesc;
	
	private Integer work;
	
	private String hobby;
	private Byte married;
	
	
	private Byte ageGroup;
	
	
	private Byte incomeLevel;
	
	
	private  Byte salary;
	
	private String province; //省份
	
	private String city; //市
	
	private String area; //区县
	
	private String thirdUid;//第三方标识
	
	private long mapprervalue;//
	
	private int num;//召回沉默用户功能时存放相距天数
	
	private String address;

	private int msgCount;//发布消息数量(目前未用)

	/**
	 * 粉丝数量(目前未用)
	 */
	private int fansCount;
	/**
	 * 关注的数量(目前未用)
	 */
	private int followCount;
	private int level;//用户等级
	
	private Double longitude; //经度

	private Double latitude; //纬度
	
	private Integer cashBalance; //广告币

	private Long donateFlag; //捐献开关(0表示关闭,1表示打开)

	private Integer redEnvelopeBalance; //余额

	public long getMapprervalue() {
		return mapprervalue;
	}

	public void setMapprervalue(long mapprervalue) {
		this.mapprervalue = mapprervalue;
	}

	public int getNum() {
		return num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public String getThirdUid() {
		return thirdUid;
	}

	public void setThirdUid(String thirdUid) {
		this.thirdUid = thirdUid;
	}

	public Byte getSalary() {
		return salary;
	}

	public void setSalary(Byte salary) {
		this.salary = salary;
	}

	public Byte getIncomeLevel() {
		return incomeLevel;
	}

	public void setIncomeLevel(Byte incomeLevel) {
		this.incomeLevel = incomeLevel;
	}

	public Byte getAgeGroup() {
		return ageGroup;
	}

	public void setAgeGroup(Byte ageGroup) {
		this.ageGroup = ageGroup;
	}

	public String getShortDesc() {
		return shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public Integer getWork() {
		return work;
	}

	public void setWork(Integer work) {
		this.work = work;
	}

	public String getHobby() {
		return hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public Byte getMarried() {
		return married;
	}

	public void setMarried(Byte married) {
		this.married = married;
	}

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	public String getPlatform() {
		return platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getBindingMobile() {
		return bindingMobile;
	}

	public void setBindingMobile(String bindingMobile) {
		this.bindingMobile = bindingMobile;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column users_13.sex
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private Integer sex;

	private String inventNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table users_13
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.table_num
	 * 
	 * @return the value of users_13.table_num
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public Integer getTableNum() {
		return tableNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.table_num
	 * 
	 * @param tableNum
	 *            the value for users_13.table_num
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setTableNum(Integer tableNum) {
		this.tableNum = tableNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.phone
	 * 
	 * @return the value of users_13.phone
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.phone
	 * 
	 * @param phone
	 *            the value for users_13.phone
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.pass_wrod
	 * 
	 * @return the value of users_13.pass_wrod
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	@JsonIgnore
	public String getPassWord() {
		return passWord;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.pass_wrod
	 * 
	 * @param passWord
	 *            the value for users_13.pass_wrod
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setPassWord(String passWord) {
		this.passWord = passWord == null ? null : passWord.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.create_time
	 * 
	 * @return the value of users_13.create_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.create_time
	 * 
	 * @param createTime
	 *            the value for users_13.create_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.modify_time
	 * 
	 * @return the value of users_13.modify_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.modify_time
	 * 
	 * @param modifyTime
	 *            the value for users_13.modify_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.private_key
	 * 
	 * @return the value of users_13.private_key
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getPrivateKey() {
		return privateKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.private_key
	 * 
	 * @param privateKey
	 *            the value for users_13.private_key
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setPrivateKey(String privateKey) {
		this.privateKey = privateKey == null ? null : privateKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.public_key
	 * 
	 * @return the value of users_13.public_key
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getPublicKey() {
		return publicKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.public_key
	 * 
	 * @param publicKey
	 *            the value for users_13.public_key
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey == null ? null : publicKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.token
	 * 
	 * @return the value of users_13.token
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.token
	 * 
	 * @param token
	 *            the value for users_13.token
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setToken(String token) {
		this.token = token == null ? null : token.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.name
	 * 
	 * @return the value of users_13.name
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.name
	 * 
	 * @param name
	 *            the value for users_13.name
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.type
	 * 
	 * @return the value of users_13.type
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.type
	 * 
	 * @param type
	 *            the value for users_13.type
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getInventNo() {
		return inventNo;
	}

	public void setInventNo(String inventNo) {
		this.inventNo = inventNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.state
	 * 
	 * @return the value of users_13.state
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.state
	 * 
	 * @param state
	 *            the value for users_13.state
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.role
	 * 
	 * @return the value of users_13.role
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.role
	 * 
	 * @param role
	 *            the value for users_13.role
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.identity_card
	 * 
	 * @return the value of users_13.identity_card
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getIdentityCard() {
		return identityCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.identity_card
	 * 
	 * @param identityCard
	 *            the value for users_13.identity_card
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setIdentityCard(String identityCard) {
		this.identityCard = identityCard == null ? null : identityCard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.birthday
	 * 
	 * @return the value of users_13.birthday
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */

	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.birthday
	 * 
	 * @param birthday
	 *            the value for users_13.birthday
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.avatar
	 * 
	 * @return the value of users_13.avatar
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.avatar
	 * 
	 * @param avatar
	 *            the value for users_13.avatar
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar == null ? null : avatar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.mid
	 * 
	 * @return the value of users_13.mid
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getMid() {
		return mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.mid
	 * 
	 * @param mid
	 *            the value for users_13.mid
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setMid(String mid) {
		this.mid = mid == null ? null : mid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.nick_name
	 * 
	 * @return the value of users_13.nick_name
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.nick_name
	 * 
	 * @param nickName
	 *            the value for users_13.nick_name
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.login_expire_time
	 * 
	 * @return the value of users_13.login_expire_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public Date getLoginExpireTime() {
		return loginExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.login_expire_time
	 * 
	 * @param loginExpireTime
	 *            the value for users_13.login_expire_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setLoginExpireTime(Date loginExpireTime) {
		this.loginExpireTime = loginExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column users_13.last_login_time
	 * 
	 * @return the value of users_13.last_login_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column users_13.last_login_time
	 * 
	 * @param lastLoginTime
	 *            the value for users_13.last_login_time
	 * 
	 * @mbggenerated Tue Jun 16 19:36:37 CST 2015
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public Date getFristLoginTime() {
		return fristLoginTime;
	}

	public void setFristLoginTime(Date fristLoginTime) {
		this.fristLoginTime = fristLoginTime;
	}

	public String getPhoneSpecification() {
		return phoneSpecification;
	}

	public void setPhoneSpecification(String phoneSpecification) {
		this.phoneSpecification = phoneSpecification;
	}

	public int getRedpackMoney() {
		return redpackMoney;
	}

	public void setRedpackMoney(int redpackMoney) {
		this.redpackMoney = redpackMoney;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public int getMsgCount() {
		return msgCount;
	}

	public void setMsgCount(int msgCount) {
		this.msgCount = msgCount;
	}

	public int getFansCount() {
		return fansCount;
	}

	public void setFansCount(int fansCount) {
		this.fansCount = fansCount;
	}

	public int getFollowCount() {
		return followCount;
	}

	public void setFollowCount(int followCount) {
		this.followCount = followCount;
	}

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Integer getCashBalance() {
		return cashBalance;
	}

	public void setCashBalance(Integer cashBalance) {
		this.cashBalance = cashBalance;
	}


	public Integer getRedEnvelopeBalance() {
		return redEnvelopeBalance;
	}

	public void setRedEnvelopeBalance(Integer redEnvelopeBalance) {
		this.redEnvelopeBalance = redEnvelopeBalance;
	}

	public Long getDonateFlag() {
		return donateFlag;
	}

	public void setDonateFlag(Long donateFlag) {
		this.donateFlag = donateFlag;
	}

	
}