package com.mouchina.moumou_server.dao.member;
import com.mouchina.base.framework.BaseMapper;
import com.mouchina.moumou_server.entity.member.UserPart;

/**
 *com.wos.mapper.UserPartMapper.java
 *2015-06-15 02:34:57
 * This was class generated by ant velocity
 */
public interface UserPartMapper extends BaseMapper<UserPart,String> {
 
}


