package com.mouchina.moumou_server.entity.message;

import java.io.Serializable;

public class SmsTemplate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.template_key
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    private String templateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.template_value
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    private String templateValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.desb
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    private String desb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_template
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.template_key
     *
     * @return the value of sms_template.template_key
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    public String getTemplateKey() {
        return templateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.template_key
     *
     * @param templateKey the value for sms_template.template_key
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    public void setTemplateKey(String templateKey) {
        this.templateKey = templateKey == null ? null : templateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.template_value
     *
     * @return the value of sms_template.template_value
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    public String getTemplateValue() {
        return templateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.template_value
     *
     * @param templateValue the value for sms_template.template_value
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    public void setTemplateValue(String templateValue) {
        this.templateValue = templateValue == null ? null : templateValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.desb
     *
     * @return the value of sms_template.desb
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    public String getDesb() {
        return desb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.desb
     *
     * @param desb the value for sms_template.desb
     *
     * @mbggenerated Tue Aug 04 21:44:55 CST 2015
     */
    public void setDesb(String desb) {
        this.desb = desb == null ? null : desb.trim();
    }
}