package com.mouchina.moumou_server.entity.social;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
/**
 * 用户评论类
 * @author Administrator
 *
 */
public class UserComment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.title
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.state
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.sequence
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.source_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long sourceId;//来源id 

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.logo
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.hot
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.parent_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long parentId;//父id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.like_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long likeSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.no_like_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long noLikeSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.tags
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.nick_name
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.user_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.collection_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long collectionSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.show_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long showSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.user_avatar
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String userAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.create_time
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.modify_time
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.video
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.audio
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String audio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.comment_type
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Byte commentType;//评论类型 1、评论   2、点赞   3、系统消息

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.comment_ext
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String commentExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.child_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long childSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.sex
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.publinsh_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private Long publinshId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.image_list
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private String imageList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_comment
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    private static final long serialVersionUID = 1L;
    
    private String parentNickName;//被评论人昵称

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.id
     *
     * @return the value of user_comment.id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.id
     *
     * @param id the value for user_comment.id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.title
     *
     * @return the value of user_comment.title
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.title
     *
     * @param title the value for user_comment.title
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.content
     *
     * @return the value of user_comment.content
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.content
     *
     * @param content the value for user_comment.content
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.state
     *
     * @return the value of user_comment.state
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.state
     *
     * @param state the value for user_comment.state
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.sequence
     *
     * @return the value of user_comment.sequence
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.sequence
     *
     * @param sequence the value for user_comment.sequence
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setSequence(Long sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.source_id
     *
     * @return the value of user_comment.source_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.source_id
     *
     * @param sourceId the value for user_comment.source_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.logo
     *
     * @return the value of user_comment.logo
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.logo
     *
     * @param logo the value for user_comment.logo
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.hot
     *
     * @return the value of user_comment.hot
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.hot
     *
     * @param hot the value for user_comment.hot
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setHot(Long hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.parent_id
     *
     * @return the value of user_comment.parent_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.parent_id
     *
     * @param parentId the value for user_comment.parent_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.like_size
     *
     * @return the value of user_comment.like_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getLikeSize() {
        return likeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.like_size
     *
     * @param likeSize the value for user_comment.like_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setLikeSize(Long likeSize) {
        this.likeSize = likeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.no_like_size
     *
     * @return the value of user_comment.no_like_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getNoLikeSize() {
        return noLikeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.no_like_size
     *
     * @param noLikeSize the value for user_comment.no_like_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setNoLikeSize(Long noLikeSize) {
        this.noLikeSize = noLikeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.tags
     *
     * @return the value of user_comment.tags
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.tags
     *
     * @param tags the value for user_comment.tags
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.nick_name
     *
     * @return the value of user_comment.nick_name
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.nick_name
     *
     * @param nickName the value for user_comment.nick_name
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.user_id
     *
     * @return the value of user_comment.user_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.user_id
     *
     * @param userId the value for user_comment.user_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.collection_size
     *
     * @return the value of user_comment.collection_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getCollectionSize() {
        return collectionSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.collection_size
     *
     * @param collectionSize the value for user_comment.collection_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setCollectionSize(Long collectionSize) {
        this.collectionSize = collectionSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.show_size
     *
     * @return the value of user_comment.show_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getShowSize() {
        return showSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.show_size
     *
     * @param showSize the value for user_comment.show_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setShowSize(Long showSize) {
        this.showSize = showSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.user_avatar
     *
     * @return the value of user_comment.user_avatar
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.user_avatar
     *
     * @param userAvatar the value for user_comment.user_avatar
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar == null ? null : userAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.create_time
     *
     * @return the value of user_comment.create_time
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.create_time
     *
     * @param createTime the value for user_comment.create_time
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.modify_time
     *
     * @return the value of user_comment.modify_time
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.modify_time
     *
     * @param modifyTime the value for user_comment.modify_time
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.video
     *
     * @return the value of user_comment.video
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.video
     *
     * @param video the value for user_comment.video
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.audio
     *
     * @return the value of user_comment.audio
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.audio
     *
     * @param audio the value for user_comment.audio
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setAudio(String audio) {
        this.audio = audio == null ? null : audio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.comment_type
     *
     * @return the value of user_comment.comment_type
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Byte getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.comment_type
     *
     * @param commentType the value for user_comment.comment_type
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setCommentType(Byte commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.comment_ext
     *
     * @return the value of user_comment.comment_ext
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getCommentExt() {
        return commentExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.comment_ext
     *
     * @param commentExt the value for user_comment.comment_ext
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setCommentExt(String commentExt) {
        this.commentExt = commentExt == null ? null : commentExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.child_size
     *
     * @return the value of user_comment.child_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getChildSize() {
        return childSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.child_size
     *
     * @param childSize the value for user_comment.child_size
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setChildSize(Long childSize) {
        this.childSize = childSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.sex
     *
     * @return the value of user_comment.sex
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.sex
     *
     * @param sex the value for user_comment.sex
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.publinsh_id
     *
     * @return the value of user_comment.publinsh_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public Long getPublinshId() {
        return publinshId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.publinsh_id
     *
     * @param publinshId the value for user_comment.publinsh_id
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setPublinshId(Long publinshId) {
        this.publinshId = publinshId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.image_list
     *
     * @return the value of user_comment.image_list
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public String getImageList() {
        return imageList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.image_list
     *
     * @param imageList the value for user_comment.image_list
     *
     * @mbggenerated Tue May 24 23:33:14 CST 2016
     */
    public void setImageList(String imageList) {
        this.imageList = imageList == null ? null : imageList.trim();
    }

	public String getParentNickName() {
		return parentNickName;
	}

	public void setParentNickName(String parentNickName) {
		this.parentNickName = parentNickName;
	}
    
    
}