package com.mouchina.moumou_server.entity.social;

import java.io.Serializable;
import java.util.Date;

public class UserInvite implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite.id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite.user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite.new_user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Long newUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite.create_time
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite.state
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite.new_user_nick_name
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private String newUserNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite.new_user_avatar
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private String newUserAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_invite.new_user_sex
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Byte newUserSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_invite
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite.id
     *
     * @return the value of user_invite.id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite.id
     *
     * @param id the value for user_invite.id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite.user_id
     *
     * @return the value of user_invite.user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite.user_id
     *
     * @param userId the value for user_invite.user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite.new_user_id
     *
     * @return the value of user_invite.new_user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Long getNewUserId() {
        return newUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite.new_user_id
     *
     * @param newUserId the value for user_invite.new_user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setNewUserId(Long newUserId) {
        this.newUserId = newUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite.create_time
     *
     * @return the value of user_invite.create_time
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite.create_time
     *
     * @param createTime the value for user_invite.create_time
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite.state
     *
     * @return the value of user_invite.state
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite.state
     *
     * @param state the value for user_invite.state
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite.new_user_nick_name
     *
     * @return the value of user_invite.new_user_nick_name
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public String getNewUserNickName() {
        return newUserNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite.new_user_nick_name
     *
     * @param newUserNickName the value for user_invite.new_user_nick_name
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setNewUserNickName(String newUserNickName) {
        this.newUserNickName = newUserNickName == null ? null : newUserNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite.new_user_avatar
     *
     * @return the value of user_invite.new_user_avatar
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public String getNewUserAvatar() {
        return newUserAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite.new_user_avatar
     *
     * @param newUserAvatar the value for user_invite.new_user_avatar
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setNewUserAvatar(String newUserAvatar) {
        this.newUserAvatar = newUserAvatar == null ? null : newUserAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_invite.new_user_sex
     *
     * @return the value of user_invite.new_user_sex
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Byte getNewUserSex() {
        return newUserSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_invite.new_user_sex
     *
     * @param newUserSex the value for user_invite.new_user_sex
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setNewUserSex(Byte newUserSex) {
        this.newUserSex = newUserSex;
    }
}