package com.mouchina.moumou_server.entity.social;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.StringUtils;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.mouchina.base.utils.UtilMaskCode;

public class UsersRelation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Long relationUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_type
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Byte relationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_user_avatar
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private String relationUserAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_user_sex
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private Byte relationUserSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.relation_user_nick_name
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private String relationUserNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_relation.create_time
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    
    private Long eventId;
    
    
   
	public Long getEventId() {
		return eventId;
	}

	public void setEventId(Long eventId) {
		this.eventId = eventId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_relation
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.id
     *
     * @return the value of users_relation.id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.id
     *
     * @param id the value for users_relation.id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.user_id
     *
     * @return the value of users_relation.user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.user_id
     *
     * @param userId the value for users_relation.user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_user_id
     *
     * @return the value of users_relation.relation_user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Long getRelationUserId() {
        return relationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_user_id
     *
     * @param relationUserId the value for users_relation.relation_user_id
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationUserId(Long relationUserId) {
        this.relationUserId = relationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_type
     *
     * @return the value of users_relation.relation_type
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Byte getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_type
     *
     * @param relationType the value for users_relation.relation_type
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationType(Byte relationType) {
        this.relationType = relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_user_avatar
     *
     * @return the value of users_relation.relation_user_avatar
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public String getRelationUserAvatar() {
        return relationUserAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_user_avatar
     *
     * @param relationUserAvatar the value for users_relation.relation_user_avatar
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationUserAvatar(String relationUserAvatar) {
        this.relationUserAvatar = relationUserAvatar == null ? null : relationUserAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_user_sex
     *
     * @return the value of users_relation.relation_user_sex
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public Byte getRelationUserSex() {
        return relationUserSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_user_sex
     *
     * @param relationUserSex the value for users_relation.relation_user_sex
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationUserSex(Byte relationUserSex) {
        this.relationUserSex = relationUserSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.relation_user_nick_name
     *
     * @return the value of users_relation.relation_user_nick_name
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public String getRelationUserNickName() {
        return relationUserNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.relation_user_nick_name
     *
     * @param relationUserNickName the value for users_relation.relation_user_nick_name
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setRelationUserNickName(String relationUserNickName) {
        this.relationUserNickName = relationUserNickName == null ? null : relationUserNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_relation.create_time
     *
     * @return the value of users_relation.create_time
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
	
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_relation.create_time
     *
     * @param createTime the value for users_relation.create_time
     *
     * @mbggenerated Mon Feb 01 16:29:32 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}