package com.mouchina.admin.service.api.vo;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class AdvertVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.id
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.advert_type
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Integer advertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.state
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.user_id
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.create_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.modify_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.start_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.end_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.red_envelope_type
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Integer redEnvelopeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.red_envelope_amount
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Integer redEnvelopeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.red_envelope_count
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Integer redEnvelopeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.advert_name
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private String advertName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.advert_content
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private String advertContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.advert_condition_city
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private String adverConditionCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.adver_condition_area
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private String adverConditionArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.adver_condition_province
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private String adverConditionProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.adver_condtion_distance
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Integer adverCondtionDistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.adver_condtion_sex
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Integer adverCondtionSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advert.adver_condtion_age_scope
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private Integer adverCondtionAgeScope;

   private String phone;
    
    
    public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advert
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.id
     *
     * @return the value of advert.id
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.id
     *
     * @param id the value for advert.id
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.advert_type
     *
     * @return the value of advert.advert_type
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Integer getAdvertType() {
        return advertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.advert_type
     *
     * @param advertType the value for advert.advert_type
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setAdvertType(Integer advertType) {
        this.advertType = advertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.state
     *
     * @return the value of advert.state
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.state
     *
     * @param state the value for advert.state
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.user_id
     *
     * @return the value of advert.user_id
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.user_id
     *
     * @param userId the value for advert.user_id
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.create_time
     *
     * @return the value of advert.create_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.create_time
     *
     * @param createTime the value for advert.create_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.modify_time
     *
     * @return the value of advert.modify_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.modify_time
     *
     * @param modifyTime the value for advert.modify_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.start_time
     *
     * @return the value of advert.start_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.start_time
     *
     * @param startTime the value for advert.start_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.end_time
     *
     * @return the value of advert.end_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.end_time
     *
     * @param endTime the value for advert.end_time
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.red_envelope_type
     *
     * @return the value of advert.red_envelope_type
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Integer getRedEnvelopeType() {
        return redEnvelopeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.red_envelope_type
     *
     * @param redEnvelopeType the value for advert.red_envelope_type
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setRedEnvelopeType(Integer redEnvelopeType) {
        this.redEnvelopeType = redEnvelopeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.red_envelope_amount
     *
     * @return the value of advert.red_envelope_amount
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Integer getRedEnvelopeAmount() {
        return redEnvelopeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.red_envelope_amount
     *
     * @param redEnvelopeAmount the value for advert.red_envelope_amount
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setRedEnvelopeAmount(Integer redEnvelopeAmount) {
        this.redEnvelopeAmount = redEnvelopeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.red_envelope_count
     *
     * @return the value of advert.red_envelope_count
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Integer getRedEnvelopeCount() {
        return redEnvelopeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.red_envelope_count
     *
     * @param redEnvelopeCount the value for advert.red_envelope_count
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setRedEnvelopeCount(Integer redEnvelopeCount) {
        this.redEnvelopeCount = redEnvelopeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.advert_name
     *
     * @return the value of advert.advert_name
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public String getAdvertName() {
        return advertName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.advert_name
     *
     * @param advertName the value for advert.advert_name
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setAdvertName(String advertName) {
        this.advertName = advertName == null ? null : advertName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.advert_content
     *
     * @return the value of advert.advert_content
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public String getAdvertContent() {
        return advertContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.advert_content
     *
     * @param advertContent the value for advert.advert_content
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setAdvertContent(String advertContent) {
        this.advertContent = advertContent == null ? null : advertContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.advert_condition_city
     *
     * @return the value of advert.advert_condition_city
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public String getAdverConditionCity() {
        return adverConditionCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.advert_condition_city
     *
     * @param adverConditionCity the value for advert.advert_condition_city
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setAdverConditionCity(String adverConditionCity) {
        this.adverConditionCity = adverConditionCity == null ? null : adverConditionCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.adver_condition_area
     *
     * @return the value of advert.adver_condition_area
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public String getAdverConditionArea() {
        return adverConditionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.adver_condition_area
     *
     * @param adverConditionArea the value for advert.adver_condition_area
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setAdverConditionArea(String adverConditionArea) {
        this.adverConditionArea = adverConditionArea == null ? null : adverConditionArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.adver_condition_province
     *
     * @return the value of advert.adver_condition_province
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public String getAdverConditionProvince() {
        return adverConditionProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.adver_condition_province
     *
     * @param adverConditionProvince the value for advert.adver_condition_province
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setAdverConditionProvince(String adverConditionProvince) {
        this.adverConditionProvince = adverConditionProvince == null ? null : adverConditionProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.adver_condtion_distance
     *
     * @return the value of advert.adver_condtion_distance
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Integer getAdverCondtionDistance() {
        return adverCondtionDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.adver_condtion_distance
     *
     * @param adverCondtionDistance the value for advert.adver_condtion_distance
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setAdverCondtionDistance(Integer adverCondtionDistance) {
        this.adverCondtionDistance = adverCondtionDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advert.adver_condtion_sex
     *
     * @return the value of advert.adver_condtion_sex
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public Integer getAdverCondtionSex() {
        return adverCondtionSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advert.adver_condtion_sex
     *
     * @param adverCondtionSex the value for advert.adver_condtion_sex
     *
     * @mbggenerated Mon Feb 01 15:47:43 CST 2016
     */
    public void setAdverCondtionSex(Integer adverCondtionSex) {
        this.adverCondtionSex = adverCondtionSex;
    }

	public Integer getAdverCondtionAgeScope() {
		return adverCondtionAgeScope;
	}

	public void setAdverCondtionAgeScope(Integer adverCondtionAgeScope) {
		this.adverCondtionAgeScope = adverCondtionAgeScope;
	}

}