package com.mouchina.admin.service.api.vo;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class AgentIncomeSumVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.id
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.user_id
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.amount
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.source_amout
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    private Integer sourceAmout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.income_date
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
  	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date incomeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.create_time
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
  	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.state
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.descb
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    private String descb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.income_size
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    private Integer incomeSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_income_sum.alone_user_income_size
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    private Integer aloneUserIncomeSize;
    
    private String phone;
    private String userName;
    
    

    public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent_income_sum
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.id
     *
     * @return the value of agent_income_sum.id
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.id
     *
     * @param id the value for agent_income_sum.id
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.user_id
     *
     * @return the value of agent_income_sum.user_id
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.user_id
     *
     * @param userId the value for agent_income_sum.user_id
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.amount
     *
     * @return the value of agent_income_sum.amount
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.amount
     *
     * @param amount the value for agent_income_sum.amount
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.source_amout
     *
     * @return the value of agent_income_sum.source_amout
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public Integer getSourceAmout() {
        return sourceAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.source_amout
     *
     * @param sourceAmout the value for agent_income_sum.source_amout
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setSourceAmout(Integer sourceAmout) {
        this.sourceAmout = sourceAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.income_date
     *
     * @return the value of agent_income_sum.income_date
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public Date getIncomeDate() {
        return incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.income_date
     *
     * @param incomeDate the value for agent_income_sum.income_date
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setIncomeDate(Date incomeDate) {
        this.incomeDate = incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.create_time
     *
     * @return the value of agent_income_sum.create_time
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.create_time
     *
     * @param createTime the value for agent_income_sum.create_time
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.state
     *
     * @return the value of agent_income_sum.state
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.state
     *
     * @param state the value for agent_income_sum.state
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.descb
     *
     * @return the value of agent_income_sum.descb
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public String getDescb() {
        return descb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.descb
     *
     * @param descb the value for agent_income_sum.descb
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setDescb(String descb) {
        this.descb = descb == null ? null : descb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.income_size
     *
     * @return the value of agent_income_sum.income_size
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public Integer getIncomeSize() {
        return incomeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.income_size
     *
     * @param incomeSize the value for agent_income_sum.income_size
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setIncomeSize(Integer incomeSize) {
        this.incomeSize = incomeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_income_sum.alone_user_income_size
     *
     * @return the value of agent_income_sum.alone_user_income_size
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public Integer getAloneUserIncomeSize() {
        return aloneUserIncomeSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_income_sum.alone_user_income_size
     *
     * @param aloneUserIncomeSize the value for agent_income_sum.alone_user_income_size
     *
     * @mbggenerated Thu May 05 16:47:12 CST 2016
     */
    public void setAloneUserIncomeSize(Integer aloneUserIncomeSize) {
        this.aloneUserIncomeSize = aloneUserIncomeSize;
    }
}