package com.mouchina.admin.service.api.vo;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class BusinessVo implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.id
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.user_id
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.business_name
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businessName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.business_address
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businessAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.business_tel
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businessTel;//商户电话

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.business_site
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businessSite;//商户网站

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.business_qq
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businessQq;//商户QQ

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.business_weixin
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businessWeixin;//商户微信

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.business_weibo
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businessWeibo;//商户微博

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.businss_credentials_up
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businssCredentialsUp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.business_credentials_down
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businessCredentialsDown;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.business_credentials_face
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private String businessCredentialsFace;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.create_time
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.modfiy_time
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date modfiyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column business.state
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private Byte state;

	private String descb;

	private String businessIndustry;

	private String businessLogo;

	private String detailAddress;

	private String phone;
	
	private Integer certificationType; //认证类型(1 个人认证 2 商户认证)

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getDetailAddress() {
		return detailAddress;
	}

	public void setDetailAddress(String detailAddress) {
		this.detailAddress = detailAddress == null ? null : detailAddress
				.trim();
	}

	public String getBusinessLogo() {
		return businessLogo;
	}

	public void setBusinessLogo(String businessLogo) {
		this.businessLogo = businessLogo == null ? null : businessLogo.trim();
	}

	public String getBusinessIndustry() {
		return businessIndustry;
	}

	public void setBusinessIndustry(String businessIndustry) {
		this.businessIndustry = businessIndustry;
	}

	public String getDescb() {
		return descb;
	}

	public void setDescb(String descb) {
		this.descb = descb;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table business
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.id
	 * 
	 * @return the value of business.id
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.id
	 * 
	 * @param id
	 *            the value for business.id
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.user_id
	 * 
	 * @return the value of business.user_id
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.user_id
	 * 
	 * @param userId
	 *            the value for business.user_id
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.business_name
	 * 
	 * @return the value of business.business_name
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinessName() {
		return businessName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.business_name
	 * 
	 * @param businessName
	 *            the value for business.business_name
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinessName(String businessName) {
		this.businessName = businessName == null ? null : businessName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.business_address
	 * 
	 * @return the value of business.business_address
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinessAddress() {
		return businessAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.business_address
	 * 
	 * @param businessAddress
	 *            the value for business.business_address
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinessAddress(String businessAddress) {
		this.businessAddress = businessAddress == null ? null : businessAddress
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.business_tel
	 * 
	 * @return the value of business.business_tel
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinessTel() {
		return businessTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.business_tel
	 * 
	 * @param businessTel
	 *            the value for business.business_tel
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinessTel(String businessTel) {
		this.businessTel = businessTel == null ? null : businessTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.business_site
	 * 
	 * @return the value of business.business_site
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinessSite() {
		return businessSite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.business_site
	 * 
	 * @param businessSite
	 *            the value for business.business_site
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinessSite(String businessSite) {
		this.businessSite = businessSite == null ? null : businessSite.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.business_qq
	 * 
	 * @return the value of business.business_qq
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinessQq() {
		return businessQq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.business_qq
	 * 
	 * @param businessQq
	 *            the value for business.business_qq
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinessQq(String businessQq) {
		this.businessQq = businessQq == null ? null : businessQq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.business_weixin
	 * 
	 * @return the value of business.business_weixin
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinessWeixin() {
		return businessWeixin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.business_weixin
	 * 
	 * @param businessWeixin
	 *            the value for business.business_weixin
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinessWeixin(String businessWeixin) {
		this.businessWeixin = businessWeixin == null ? null : businessWeixin
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.business_weibo
	 * 
	 * @return the value of business.business_weibo
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinessWeibo() {
		return businessWeibo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.business_weibo
	 * 
	 * @param businessWeibo
	 *            the value for business.business_weibo
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinessWeibo(String businessWeibo) {
		this.businessWeibo = businessWeibo == null ? null : businessWeibo
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.businss_credentials_up
	 * 
	 * @return the value of business.businss_credentials_up
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinssCredentialsUp() {
		return businssCredentialsUp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.businss_credentials_up
	 * 
	 * @param businssCredentialsUp
	 *            the value for business.businss_credentials_up
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinssCredentialsUp(String businssCredentialsUp) {
		this.businssCredentialsUp = businssCredentialsUp == null ? null
				: businssCredentialsUp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.business_credentials_down
	 * 
	 * @return the value of business.business_credentials_down
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinessCredentialsDown() {
		return businessCredentialsDown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.business_credentials_down
	 * 
	 * @param businessCredentialsDown
	 *            the value for business.business_credentials_down
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinessCredentialsDown(String businessCredentialsDown) {
		this.businessCredentialsDown = businessCredentialsDown == null ? null
				: businessCredentialsDown.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.business_credentials_face
	 * 
	 * @return the value of business.business_credentials_face
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public String getBusinessCredentialsFace() {
		return businessCredentialsFace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.business_credentials_face
	 * 
	 * @param businessCredentialsFace
	 *            the value for business.business_credentials_face
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setBusinessCredentialsFace(String businessCredentialsFace) {
		this.businessCredentialsFace = businessCredentialsFace == null ? null
				: businessCredentialsFace.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.create_time
	 * 
	 * @return the value of business.create_time
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.create_time
	 * 
	 * @param createTime
	 *            the value for business.create_time
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.modfiy_time
	 * 
	 * @return the value of business.modfiy_time
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public Date getModfiyTime() {
		return modfiyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.modfiy_time
	 * 
	 * @param modfiyTime
	 *            the value for business.modfiy_time
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setModfiyTime(Date modfiyTime) {
		this.modfiyTime = modfiyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column business.state
	 * 
	 * @return the value of business.state
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public Byte getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column business.state
	 * 
	 * @param state
	 *            the value for business.state
	 * 
	 * @mbggenerated Mon Feb 01 16:24:57 CST 2016
	 */
	public void setState(Byte state) {
		this.state = state;
	}

	public Integer getCertificationType() {
		return certificationType;
	}

	public void setCertificationType(Integer certificationType) {
		this.certificationType = certificationType;
	}
}