package com.mouchina.moumou_server.entity.pay;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class UserCashFlow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.cash_flow_no
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private String cashFlowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.price
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.create_time
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.cash_flow_type
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Byte cashFlowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.user_id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.cash_flow_title
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private String cashFlowTitle;

    private String tableNum;
    
    public String getTableNum() {
		return tableNum;
	}

	public void setTableNum(String tableNum) {
		this.tableNum = tableNum;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.trigger_no
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private String triggerNo;
    
    private Integer balance;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_cash_flow_2015
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private static final long serialVersionUID = 1L;

    public Integer getBalance() {
		return balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.id
     *
     * @return the value of user_cash_flow_2015.id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.id
     *
     * @param id the value for user_cash_flow_2015.id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.cash_flow_no
     *
     * @return the value of user_cash_flow_2015.cash_flow_no
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public String getCashFlowNo() {
        return cashFlowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.cash_flow_no
     *
     * @param cashFlowNo the value for user_cash_flow_2015.cash_flow_no
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setCashFlowNo(String cashFlowNo) {
        this.cashFlowNo = cashFlowNo == null ? null : cashFlowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.price
     *
     * @return the value of user_cash_flow_2015.price
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.price
     *
     * @param price the value for user_cash_flow_2015.price
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.create_time
     *
     * @return the value of user_cash_flow_2015.create_time
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.create_time
     *
     * @param createTime the value for user_cash_flow_2015.create_time
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.cash_flow_type
     *
     * @return the value of user_cash_flow_2015.cash_flow_type
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Byte getCashFlowType() {
        return cashFlowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.cash_flow_type
     *
     * @param cashFlowType the value for user_cash_flow_2015.cash_flow_type
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setCashFlowType(Byte cashFlowType) {
        this.cashFlowType = cashFlowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.user_id
     *
     * @return the value of user_cash_flow_2015.user_id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.user_id
     *
     * @param userId the value for user_cash_flow_2015.user_id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.cash_flow_title
     *
     * @return the value of user_cash_flow_2015.cash_flow_title
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public String getCashFlowTitle() {
        return cashFlowTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.cash_flow_title
     *
     * @param cashFlowTitle the value for user_cash_flow_2015.cash_flow_title
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setCashFlowTitle(String cashFlowTitle) {
        this.cashFlowTitle = cashFlowTitle == null ? null : cashFlowTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.trigger_no
     *
     * @return the value of user_cash_flow_2015.trigger_no
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public String getTriggerNo() {
        return triggerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.trigger_no
     *
     * @param triggerNo the value for user_cash_flow_2015.trigger_no
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setTriggerNo(String triggerNo) {
        this.triggerNo = triggerNo == null ? null : triggerNo.trim();
    }
}