package com.mouchina.moumou_server.entity.pay;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class UserReimburse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.id
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.reimburse_no
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private String reimburseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.state
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.reimburse_cause
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private String reimburseCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.reimburse_type
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private Byte reimburseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.order_detail_nos
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private String orderDetailNos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.user_id
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.price
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.order_no
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.process_bak
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private String processBak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.create_time
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.modify_time
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private  Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.fininsh_time
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date fininshTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_reimburse_2015.teacher_ids
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private String teacherIds;

    private String payNo;

    private String batchNo;

    public String getPayNo() {
		return payNo;
	}

	public void setPayNo(String payNo) {
		this.payNo = payNo;
	}

    public String getBatchNo() {
        return batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    private String tableNum;
    
    public String getTableNum() {
		return tableNum;
	}

	public void setTableNum(String tableNum) {
		this.tableNum = tableNum;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_reimburse_2015
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.id
     *
     * @return the value of user_reimburse_2015.id
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.id
     *
     * @param id the value for user_reimburse_2015.id
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.reimburse_no
     *
     * @return the value of user_reimburse_2015.reimburse_no
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public String getReimburseNo() {
        return reimburseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.reimburse_no
     *
     * @param reimburseNo the value for user_reimburse_2015.reimburse_no
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setReimburseNo(String reimburseNo) {
        this.reimburseNo = reimburseNo == null ? null : reimburseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.state
     *
     * @return the value of user_reimburse_2015.state
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.state
     *
     * @param state the value for user_reimburse_2015.state
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.reimburse_cause
     *
     * @return the value of user_reimburse_2015.reimburse_cause
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public String getReimburseCause() {
        return reimburseCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.reimburse_cause
     *
     * @param reimburseCause the value for user_reimburse_2015.reimburse_cause
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setReimburseCause(String reimburseCause) {
        this.reimburseCause = reimburseCause == null ? null : reimburseCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.reimburse_type
     *
     * @return the value of user_reimburse_2015.reimburse_type
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public Byte getReimburseType() {
        return reimburseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.reimburse_type
     *
     * @param reimburseType the value for user_reimburse_2015.reimburse_type
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setReimburseType(Byte reimburseType) {
        this.reimburseType = reimburseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.order_detail_nos
     *
     * @return the value of user_reimburse_2015.order_detail_nos
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public String getOrderDetailNos() {
        return orderDetailNos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.order_detail_nos
     *
     * @param orderDetailNos the value for user_reimburse_2015.order_detail_nos
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setOrderDetailNos(String orderDetailNos) {
        this.orderDetailNos = orderDetailNos == null ? null : orderDetailNos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.user_id
     *
     * @return the value of user_reimburse_2015.user_id
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.user_id
     *
     * @param userId the value for user_reimburse_2015.user_id
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.price
     *
     * @return the value of user_reimburse_2015.price
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.price
     *
     * @param price the value for user_reimburse_2015.price
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.order_no
     *
     * @return the value of user_reimburse_2015.order_no
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.order_no
     *
     * @param orderNo the value for user_reimburse_2015.order_no
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.process_bak
     *
     * @return the value of user_reimburse_2015.process_bak
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public String getProcessBak() {
        return processBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.process_bak
     *
     * @param processBak the value for user_reimburse_2015.process_bak
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setProcessBak(String processBak) {
        this.processBak = processBak == null ? null : processBak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.create_time
     *
     * @return the value of user_reimburse_2015.create_time
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.create_time
     *
     * @param createTime the value for user_reimburse_2015.create_time
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.modify_time
     *
     * @return the value of user_reimburse_2015.modify_time
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.modify_time
     *
     * @param modifyTime the value for user_reimburse_2015.modify_time
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.fininsh_time
     *
     * @return the value of user_reimburse_2015.fininsh_time
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public Date getFininshTime() {
        return fininshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.fininsh_time
     *
     * @param fininshTime the value for user_reimburse_2015.fininsh_time
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setFininshTime(Date fininshTime) {
        this.fininshTime = fininshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reimburse_2015.teacher_ids
     *
     * @return the value of user_reimburse_2015.teacher_ids
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public String getTeacherIds() {
        return teacherIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reimburse_2015.teacher_ids
     *
     * @param teacherIds the value for user_reimburse_2015.teacher_ids
     *
     * @mbggenerated Sat Aug 01 17:18:28 CST 2015
     */
    public void setTeacherIds(String teacherIds) {
        this.teacherIds = teacherIds == null ? null : teacherIds.trim();
    }
}