package com.mouchina.moumou_server.entity.order;

import java.io.Serializable;
import java.util.Date;

public class OrdersDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.order_detail_no
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private String orderDetailNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.title
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.goods_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.order_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.order_desc
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private String orderDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.order_bak
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private String orderBak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.order_state
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Byte orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.goods_count
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Integer goodsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.create_time
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.modify_time
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.unit_pirce
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Integer unitPirce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.count_price
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Integer countPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.order_count_price
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Integer orderCountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.order_unit_price
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Integer orderUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.start_time
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.start_end
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.consume_type
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Byte consumeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.insurance_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Long insuranceId;
    
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail_2015_0.snapshop_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private Long snapshopId;

    private Long coursePublicId;
    
    private Integer teacherId;
    private String teacherName;
    
    
    private  Byte scheduleState;
    
    private  Byte isComment;
    
    private String babyIds;
    
    private Integer  extraBabysCount;
    
    private String coursePublicIds;
    
    private String goodsIds;
    private String allotTime;
    
    
    public String getGoodsIds() {
		return goodsIds;
	}

	public void setGoodsIds(String goodsIds) {
		this.goodsIds = goodsIds;
	}

	public String getAllotTime() {
		return allotTime;
	}

	public void setAllotTime(String allotTime) {
		this.allotTime = allotTime;
	}

	public String getCoursePublicIds() {
		return coursePublicIds;
	}

	public void setCoursePublicIds(String coursePublicIds) {
		this.coursePublicIds = coursePublicIds;
	}

	public Integer getExtraBabysCount() {
		return extraBabysCount;
	}

	public void setExtraBabysCount(Integer extraBabysCount) {
		this.extraBabysCount = extraBabysCount;
	}

	public String getBabyIds() {
		return babyIds;
	}

	public void setBabyIds(String babyIds) {
		this.babyIds = babyIds;
	}

	public Byte getIsComment() {
		return isComment;
	}

	public void setIsComment(Byte isComment) {
		this.isComment = isComment;
	}

	public Byte getScheduleState() {
		return scheduleState;
	}

	public void setScheduleState(Byte scheduleState) {
		this.scheduleState = scheduleState;
	}

	public Integer getTeacherId() {
		return teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	
    public Byte getOrderState() {
		return orderState;
	}

	public void setOrderState(Byte orderState) {
		this.orderState = orderState;
	}

	public Byte getConsumeType() {
		return consumeType;
	}

	public void setConsumeType(Byte consumeType) {
		this.consumeType = consumeType;
	}

	public Long getCoursePublicId() {
		return coursePublicId;
	}

	public void setCoursePublicId(Long coursePublicId) {
		this.coursePublicId = coursePublicId;
	}

	private String tableNum;
    
    private String orderTableNum;

    public String getTableNum() {
		return tableNum;
	}

	public void setTableNum(String tableNum) {
		this.tableNum = tableNum;
	}

	public String getOrderTableNum() {
		return orderTableNum;
	}

	public void setOrderTableNum(String orderTableNum) {
		this.orderTableNum = orderTableNum;
	}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders_detail_2015_0
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.id
     *
     * @return the value of orders_detail_2015_0.id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.id
     *
     * @param id the value for orders_detail_2015_0.id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.order_detail_no
     *
     * @return the value of orders_detail_2015_0.order_detail_no
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public String getOrderDetailNo() {
        return orderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.order_detail_no
     *
     * @param orderDetailNo the value for orders_detail_2015_0.order_detail_no
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setOrderDetailNo(String orderDetailNo) {
        this.orderDetailNo = orderDetailNo == null ? null : orderDetailNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.title
     *
     * @return the value of orders_detail_2015_0.title
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.title
     *
     * @param title the value for orders_detail_2015_0.title
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.goods_id
     *
     * @return the value of orders_detail_2015_0.goods_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.goods_id
     *
     * @param goodsId the value for orders_detail_2015_0.goods_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

 
    public String getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.order_desc
     *
     * @return the value of orders_detail_2015_0.order_desc
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public String getOrderDesc() {
        return orderDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.order_desc
     *
     * @param orderDesc the value for orders_detail_2015_0.order_desc
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setOrderDesc(String orderDesc) {
        this.orderDesc = orderDesc == null ? null : orderDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.order_bak
     *
     * @return the value of orders_detail_2015_0.order_bak
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public String getOrderBak() {
        return orderBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.order_bak
     *
     * @param orderBak the value for orders_detail_2015_0.order_bak
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setOrderBak(String orderBak) {
        this.orderBak = orderBak == null ? null : orderBak.trim();
    }

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.goods_count
     *
     * @return the value of orders_detail_2015_0.goods_count
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.goods_count
     *
     * @param goodsCount the value for orders_detail_2015_0.goods_count
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.create_time
     *
     * @return the value of orders_detail_2015_0.create_time
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.create_time
     *
     * @param createTime the value for orders_detail_2015_0.create_time
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.modify_time
     *
     * @return the value of orders_detail_2015_0.modify_time
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.modify_time
     *
     * @param modifyTime the value for orders_detail_2015_0.modify_time
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.unit_pirce
     *
     * @return the value of orders_detail_2015_0.unit_pirce
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Integer getUnitPirce() {
        return unitPirce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.unit_pirce
     *
     * @param unitPirce the value for orders_detail_2015_0.unit_pirce
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setUnitPirce(Integer unitPirce) {
        this.unitPirce = unitPirce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.count_price
     *
     * @return the value of orders_detail_2015_0.count_price
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Integer getCountPrice() {
        return countPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.count_price
     *
     * @param countPrice the value for orders_detail_2015_0.count_price
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setCountPrice(Integer countPrice) {
        this.countPrice = countPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.order_count_price
     *
     * @return the value of orders_detail_2015_0.order_count_price
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Integer getOrderCountPrice() {
        return orderCountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.order_count_price
     *
     * @param orderCountPrice the value for orders_detail_2015_0.order_count_price
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setOrderCountPrice(Integer orderCountPrice) {
        this.orderCountPrice = orderCountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.order_unit_price
     *
     * @return the value of orders_detail_2015_0.order_unit_price
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Integer getOrderUnitPrice() {
        return orderUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.order_unit_price
     *
     * @param orderUnitPrice the value for orders_detail_2015_0.order_unit_price
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setOrderUnitPrice(Integer orderUnitPrice) {
        this.orderUnitPrice = orderUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.start_time
     *
     * @return the value of orders_detail_2015_0.start_time
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.start_time
     *
     * @param startTime the value for orders_detail_2015_0.start_time
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

   

  

    public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.insurance_id
     *
     * @return the value of orders_detail_2015_0.insurance_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Long getInsuranceId() {
        return insuranceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.insurance_id
     *
     * @param insuranceId the value for orders_detail_2015_0.insurance_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setInsuranceId(Long insuranceId) {
        this.insuranceId = insuranceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail_2015_0.snapshop_id
     *
     * @return the value of orders_detail_2015_0.snapshop_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public Long getSnapshopId() {
        return snapshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail_2015_0.snapshop_id
     *
     * @param snapshopId the value for orders_detail_2015_0.snapshop_id
     *
     * @mbggenerated Mon Jun 15 13:12:26 CST 2015
     */
    public void setSnapshopId(Long snapshopId) {
        this.snapshopId = snapshopId;
    }
}