package com.mouchina.moumou_server.entity.permission;

import java.io.Serializable;

public class StaticUserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_user_role.id
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_user_role.user_id
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_user_role.user_phone
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_user_role.role_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_user_role.user_role_note
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private String userRoleNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table static_user_role
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_user_role.id
     *
     * @return the value of static_user_role.id
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_user_role.id
     *
     * @param id the value for static_user_role.id
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_user_role.user_id
     *
     * @return the value of static_user_role.user_id
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_user_role.user_id
     *
     * @param userId the value for static_user_role.user_id
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_user_role.user_phone
     *
     * @return the value of static_user_role.user_phone
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_user_role.user_phone
     *
     * @param userPhone the value for static_user_role.user_phone
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_user_role.role_code
     *
     * @return the value of static_user_role.role_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_user_role.role_code
     *
     * @param roleId the value for static_user_role.role_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_user_role.user_role_note
     *
     * @return the value of static_user_role.user_role_note
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public String getUserRoleNote() {
        return userRoleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_user_role.user_role_note
     *
     * @param userRoleNote the value for static_user_role.user_role_note
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setUserRoleNote(String userRoleNote) {
        this.userRoleNote = userRoleNote == null ? null : userRoleNote.trim();
    }
}