package com.mouchina.moumou_server.entity.permission;

import java.io.Serializable;

public class StaticRole implements Serializable {

    private Long roleId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_role.role_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private String  roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_role.role_name
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_role.role_note
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private String roleNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table static_role
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_role.role_code
     *
     * @return the value of static_role.role_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_role.role_code
     *
     * @param roleCode the value for static_role.role_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_role.role_name
     *
     * @return the value of static_role.role_name
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_role.role_name
     *
     * @param roleName the value for static_role.role_name
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_role.role_note
     *
     * @return the value of static_role.role_note
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public String getRoleNote() {
        return roleNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_role.role_note
     *
     * @param roleNote the value for static_role.role_note
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setRoleNote(String roleNote) {
        this.roleNote = roleNote == null ? null : roleNote.trim();
    }
}