package com.mouchina.moumou_server.entity.permission;

import java.io.Serializable;

public class StaticRolePermission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_role_permission.role_permission_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_role_permission.role_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_role_permission.permission_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_role_permission.role_permission_note
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private String rolePermissionNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table static_role_permission
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_role_permission.role_permission_code
     *
     * @return the value of static_role_permission.role_permission_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_role_permission.role_permission_code
     *
     * @param id the value for static_role_permission.role_permission_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setId(Long id) {
        this.id = id ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_role_permission.role_code
     *
     * @return the value of static_role_permission.role_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_role_permission.role_code
     *
     * @param roleId the value for static_role_permission.role_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_role_permission.permission_code
     *
     * @return the value of static_role_permission.permission_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_role_permission.permission_code
     *
     * @param permissionId the value for static_role_permission.permission_code
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_role_permission.role_permission_note
     *
     * @return the value of static_role_permission.role_permission_note
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public String getRolePermissionNote() {
        return rolePermissionNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_role_permission.role_permission_note
     *
     * @param rolePermissionNote the value for static_role_permission.role_permission_note
     *
     * @mbggenerated Thu Nov 12 15:10:21 CST 2015
     */
    public void setRolePermissionNote(String rolePermissionNote) {
        this.rolePermissionNote = rolePermissionNote == null ? null : rolePermissionNote.trim();
    }
}